image: php:7.3

stages:
  - build
  - test

services:
  - mysql:5.6

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

variables:
  MYSQL_DATABASE: "facturini"
  MYSQL_ROOT_PASSWORD: "dbpwd"
  MYSQL_HOST: "mysql"
  MYSQL_USER: "gitlabci"
  MYSQL_PASSWORD: "dbpwd"

build:
  stage: build
  script:
    - apt-get update -yqq
    - apt-get install git zip -yqq
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install

test:behat:
  stage: test
  before_script:
    - bash ci/docker_install.sh > /dev/null
  script:
    - vendor/bin/behat --colors
