language: php

php:
  - '7.3'

env:
  - MYSQL_USER=travis MYSQL_PASSWORD=dbpwd MYSQL_DATABASE=facturini

notifications:
  email:
    recipients:
      - danieltomefer@gmail.com
    on_success: never
    on_failure: always

services:
  - mysql

before_install:
  - composer self-update
  - mysql -u travis db/factura.sql

install:
  - composer install

script:
  - vendor/bin/behat
