language: php

php:
  - '7.3'

env:
  - MYSQL_USER=troll
  - MYSQL_PASSWORD=dbpwd
  - MYSQL_DATABASE=facturini

notifications:
  email:
    recipients:
      - danieltomefer@gmail.com
    on_success: never
    on_failure: always

before_script:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/behat
