version: '3.2'

services:
  php-apache:
    build: docker/php7.3-apache/.
    image: php:7.3-apache
    env_file: docker/.env
    ports:
      - "8080:80"
    links:
      - db:mysql
    volumes:
      - .:/var/www/html

  db:
    image: mysql:5.6
    command: --bind-address=0.0.0.0 --max-connections=1500
    ports:
      - "6033:3306"
    env_file: docker/.env
    volumes:
      - ./.mysqldata:/var/lib/mysql

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin:4.7
#    ports:
#      - "8888:80"
#    env_file: docker/.env
#    links:
#      - mysql:db

volumes:
  .mysqldata:
    driver: local